-- Indicative installed rates supplied by SUPPLYBASE.
-- Both brands use the same ranges from the supplied catalogue.
-- Rate ranges are informational, not fixed booking charges.
-- Existing Dr. Fixit rates are preserved.

SET @wp_category_id = (
    SELECT id FROM service_categories WHERE slug = 'waterproofing'
);

INSERT INTO service_options
    (category_id, step_no, question_key, question_text,
     input_type, required, option_value, option_label,
     option_hint, option_group, price_paise, sort_order)
VALUES
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'acrylic-asian-paints', 'Acrylic Waterproofing', '₹70 - ₹90 / sq. ft.', 'Asian Paints', NULL, 1),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'pu-asian-paints', 'PU Waterproofing', '₹110 - ₹140 / sq. ft.', 'Asian Paints', NULL, 2),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'cementitious-asian-paints', 'Cementitious Waterproofing', '₹90 - ₹120 / sq. ft.', 'Asian Paints', NULL, 3),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'existing-surface-asian-paints', 'Tile / Existing Surface Waterproofing', '₹80 - ₹110 / sq. ft.', 'Asian Paints', NULL, 4),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-asian-paints', 'Crack & Joint Treatment', '₹60 - ₹90 / sq. ft.', 'Asian Paints', NULL, 5),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'drainage-finishing-asian-paints', 'Drainage & Protective Finishing', '₹50 - ₹80 / sq. ft.', 'Asian Paints', NULL, 6),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'acrylic-berger', 'Acrylic Waterproofing', '₹70 - ₹90 / sq. ft.', 'Berger', NULL, 1),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'pu-berger', 'PU Waterproofing', '₹110 - ₹140 / sq. ft.', 'Berger', NULL, 2),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'cementitious-berger', 'Cementitious Waterproofing', '₹90 - ₹120 / sq. ft.', 'Berger', NULL, 3),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'existing-surface-berger', 'Tile / Existing Surface Waterproofing', '₹80 - ₹110 / sq. ft.', 'Berger', NULL, 4),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-berger', 'Crack & Joint Treatment', '₹60 - ₹90 / sq. ft.', 'Berger', NULL, 5),
(@wp_category_id, 31, 'wp_terrace_rates', 'Terrace Waterproofing rates', 'SINGLE', FALSE, 'drainage-finishing-berger', 'Drainage & Protective Finishing', '₹50 - ₹80 / sq. ft.', 'Berger', NULL, 6),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'cementitious-asian-paints', 'Cementitious Waterproofing', '₹45 - ₹65 / sq. ft.', 'Asian Paints', NULL, 1),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'acrylic-asian-paints', 'Acrylic Waterproofing', '₹40 - ₹60 / sq. ft.', 'Asian Paints', NULL, 2),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'pu-asian-paints', 'PU Waterproofing', '₹90 - ₹130 / sq. ft.', 'Asian Paints', NULL, 3),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'wet-area-asian-paints', 'Wet Area / Tile Waterproofing', '₹55 - ₹80 / sq. ft.', 'Asian Paints', NULL, 4),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-asian-paints', 'Crack & Joint Treatment', '₹50 - ₹80 / sq. ft.', 'Asian Paints', NULL, 5),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'pipe-drain-asian-paints', 'Pipe & Drain Sealing', '₹40 - ₹70 / sq. ft.', 'Asian Paints', NULL, 6),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'cementitious-berger', 'Cementitious Waterproofing', '₹45 - ₹65 / sq. ft.', 'Berger', NULL, 1),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'acrylic-berger', 'Acrylic Waterproofing', '₹40 - ₹60 / sq. ft.', 'Berger', NULL, 2),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'pu-berger', 'PU Waterproofing', '₹90 - ₹130 / sq. ft.', 'Berger', NULL, 3),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'wet-area-berger', 'Wet Area / Tile Waterproofing', '₹55 - ₹80 / sq. ft.', 'Berger', NULL, 4),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-berger', 'Crack & Joint Treatment', '₹50 - ₹80 / sq. ft.', 'Berger', NULL, 5),
(@wp_category_id, 33, 'wp_bathroom_floor_rates', 'Bathroom Waterproofing rates', 'SINGLE', FALSE, 'pipe-drain-berger', 'Pipe & Drain Sealing', '₹40 - ₹70 / sq. ft.', 'Berger', NULL, 6),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'anti-damp-asian-paints', 'Damp / Anti-Damp Treatment', '₹45 - ₹65 / sq. ft.', 'Asian Paints', NULL, 1),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'interior-coating-asian-paints', 'Interior Waterproofing Coating', '₹50 - ₹75 / sq. ft.', 'Asian Paints', NULL, 2),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'cementitious-asian-paints', 'Cementitious Treatment', '₹60 - ₹85 / sq. ft.', 'Asian Paints', NULL, 3),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-asian-paints', 'Crack & Joint Treatment', '₹40 - ₹70 / sq. ft.', 'Asian Paints', NULL, 4),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'seepage-coating-asian-paints', 'Seepage Treatment + Waterproof Coating', '₹70 - ₹100 / sq. ft.', 'Asian Paints', NULL, 5),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'putty-primer-paint-asian-paints', 'Waterproof Putty + Primer + Paint Finish', '₹80 - ₹120 / sq. ft.', 'Asian Paints', NULL, 6),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'anti-damp-berger', 'Damp / Anti-Damp Treatment', '₹45 - ₹65 / sq. ft.', 'Berger', NULL, 1),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'interior-coating-berger', 'Interior Waterproofing Coating', '₹50 - ₹75 / sq. ft.', 'Berger', NULL, 2),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'cementitious-berger', 'Cementitious Treatment', '₹60 - ₹85 / sq. ft.', 'Berger', NULL, 3),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-berger', 'Crack & Joint Treatment', '₹40 - ₹70 / sq. ft.', 'Berger', NULL, 4),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'seepage-coating-berger', 'Seepage Treatment + Waterproof Coating', '₹70 - ₹100 / sq. ft.', 'Berger', NULL, 5),
(@wp_category_id, 34, 'wp_interior_rates', 'Interior Wall Waterproofing rates', 'SINGLE', FALSE, 'putty-primer-paint-berger', 'Waterproof Putty + Primer + Paint Finish', '₹80 - ₹120 / sq. ft.', 'Berger', NULL, 6),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'exterior-coating-asian-paints', 'Exterior Waterproofing Coating', '₹50 - ₹70 / sq. ft.', 'Asian Paints', NULL, 1),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'acrylic-asian-paints', 'Acrylic Exterior Waterproofing', '₹55 - ₹80 / sq. ft.', 'Asian Paints', NULL, 2),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'cementitious-asian-paints', 'Cementitious Waterproofing', '₹60 - ₹85 / sq. ft.', 'Asian Paints', NULL, 3),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-asian-paints', 'Crack & Joint Treatment', '₹40 - ₹70 / sq. ft.', 'Asian Paints', NULL, 4),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'seepage-dampness-asian-paints', 'Seepage / Dampness Treatment', '₹70 - ₹100 / sq. ft.', 'Asian Paints', NULL, 5),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'exterior-paint-asian-paints', 'Waterproofing + Exterior Paint Finish', '₹90 - ₹130 / sq. ft.', 'Asian Paints', NULL, 6),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'exterior-coating-berger', 'Exterior Waterproofing Coating', '₹50 - ₹70 / sq. ft.', 'Berger', NULL, 1),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'acrylic-berger', 'Acrylic Exterior Waterproofing', '₹55 - ₹80 / sq. ft.', 'Berger', NULL, 2),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'cementitious-berger', 'Cementitious Waterproofing', '₹60 - ₹85 / sq. ft.', 'Berger', NULL, 3),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-berger', 'Crack & Joint Treatment', '₹40 - ₹70 / sq. ft.', 'Berger', NULL, 4),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'seepage-dampness-berger', 'Seepage / Dampness Treatment', '₹70 - ₹100 / sq. ft.', 'Berger', NULL, 5),
(@wp_category_id, 32, 'wp_exterior_rates', 'Exterior Wall Waterproofing rates', 'SINGLE', FALSE, 'exterior-paint-berger', 'Waterproofing + Exterior Paint Finish', '₹90 - ₹130 / sq. ft.', 'Berger', NULL, 6),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'cementitious-asian-paints', 'Cementitious Waterproofing', '₹70 - ₹100 / sq. ft.', 'Asian Paints', NULL, 1),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'acrylic-asian-paints', 'Acrylic Waterproofing Coating', '₹60 - ₹90 / sq. ft.', 'Asian Paints', NULL, 2),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'pu-asian-paints', 'PU Waterproofing', '₹120 - ₹160 / sq. ft.', 'Asian Paints', NULL, 3),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-asian-paints', 'Crack & Joint Treatment', '₹60 - ₹100 / sq. ft.', 'Asian Paints', NULL, 4),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'joint-pipe-asian-paints', 'Construction Joint / Pipe Sealing', '₹70 - ₹110 / sq. ft.', 'Asian Paints', NULL, 5),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'complete-system-asian-paints', 'Complete Basement Waterproofing System', '₹140 - ₹200 / sq. ft.', 'Asian Paints', NULL, 6),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'cementitious-berger', 'Cementitious Waterproofing', '₹70 - ₹100 / sq. ft.', 'Berger', NULL, 1),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'acrylic-berger', 'Acrylic Waterproofing Coating', '₹60 - ₹90 / sq. ft.', 'Berger', NULL, 2),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'pu-berger', 'PU Waterproofing', '₹120 - ₹160 / sq. ft.', 'Berger', NULL, 3),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-berger', 'Crack & Joint Treatment', '₹60 - ₹100 / sq. ft.', 'Berger', NULL, 4),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'joint-pipe-berger', 'Construction Joint / Pipe Sealing', '₹70 - ₹110 / sq. ft.', 'Berger', NULL, 5),
(@wp_category_id, 36, 'wp_basement_rates', 'Basement Waterproofing rates', 'SINGLE', FALSE, 'complete-system-berger', 'Complete Basement Waterproofing System', '₹140 - ₹200 / sq. ft.', 'Berger', NULL, 6),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'cementitious-asian-paints', 'Cementitious Waterproofing', '₹70 - ₹100 / sq. ft.', 'Asian Paints', NULL, 1),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, '2k-cementitious-asian-paints', '2K Cementitious Waterproofing', '₹80 - ₹120 / sq. ft.', 'Asian Paints', NULL, 2),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-asian-paints', 'Crack & Joint Treatment', '₹60 - ₹90 / sq. ft.', 'Asian Paints', NULL, 3),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'pipe-sealing-asian-paints', 'Pipe / Inlet / Outlet Sealing', '₹70 - ₹110 / sq. ft.', 'Asian Paints', NULL, 4),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'complete-system-asian-paints', 'Complete Water Tank Waterproofing', '₹100 - ₹150 / sq. ft.', 'Asian Paints', NULL, 5),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'cementitious-berger', 'Cementitious Waterproofing', '₹70 - ₹100 / sq. ft.', 'Berger', NULL, 1),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, '2k-cementitious-berger', '2K Cementitious Waterproofing', '₹80 - ₹120 / sq. ft.', 'Berger', NULL, 2),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'crack-joint-berger', 'Crack & Joint Treatment', '₹60 - ₹90 / sq. ft.', 'Berger', NULL, 3),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'pipe-sealing-berger', 'Pipe / Inlet / Outlet Sealing', '₹70 - ₹110 / sq. ft.', 'Berger', NULL, 4),
(@wp_category_id, 35, 'wp_water_tank_rates', 'Water Tank Waterproofing rates', 'SINGLE', FALSE, 'complete-system-berger', 'Complete Water Tank Waterproofing', '₹100 - ₹150 / sq. ft.', 'Berger', NULL, 5);
